apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: backend
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        app.kubernetes.io/component: backend
    spec:
      containers:
        - image: quay.io/srcmaxim/gradle-example-app:latest
          name: app
          ports:
            - containerPort: 8080
