apiVersion: v1
kind: Service
metadata:
  name: app-node-port
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 80
  #clusterIP: <public ip>
