FROM gradle:7.0.2-jdk11-hotspot@sha256:d770ad49ca32abd718ce865cb3176bb4a1c7ed56ae69f9a0bc14fc9b8851ba5c AS build
RUN mkdir /project
COPY . /project
WORKDIR /project
RUN gradle :services:app:build

FROM adoptopenjdk/openjdk11:jre-11.0.11_9-alpine@sha256:69c257f50bbc4b47a701c6cb0686f1c20bc437a127cb2315ceb671b86718cd15
RUN apk add dumb-init
RUN mkdir /app
RUN addgroup --system javauser && adduser -S -s /bin/false -G javauser javauser
COPY --from=build /project/services/app/build/libs/*.jar /app/app.jar
WORKDIR /app
RUN chown -R javauser:javauser /app
USER javauser
CMD "dumb-init" "java" "-jar" "app.jar"
