FROM gradle:7.0.2-jdk16-hotspot@sha256:3d55e29e1148482fe65f5de9ddb01f2d9cae1a31c4bcce414069359c6308b288 as build
RUN mkdir /project
COPY . /project
WORKDIR /project
RUN gradle :services:app:build --stacktrace

FROM adoptopenjdk/openjdk16:jre-16.0.1_9-alpine@sha256:a11de1a80a8d41396832620c3fb8345abe8a6f1b6fca72bb12772878f3d8f9e4
RUN apk add dumb-init
RUN mkdir /app
RUN addgroup --system javauser && adduser -S -s /bin/false -G javauser javauser
COPY --from=build /project/services/app/build/libs/*.jar /app/app.jar
WORKDIR /app
RUN chown -R javauser:javauser /app
USER javauser
CMD "dumb-init" "java" "-jar" "app.jar"
